# Generated by Rokct Backend Composer

# --- BEG OF DYNAMIC SDK COMMANDS ---
commands = globals().get('commands', [])
# --- Module: agent ---
from rcore.agent.brain.commands import update_tenant_ecosystem_command as _sdk_command_0
if _sdk_command_0 not in commands: commands.append(_sdk_command_0)
# --- END OF DYNAMIC SDK COMMANDS ---
