# Copyright (c) 2026 ROKCT INTELLIGENCE (PTY) LTD
# For license information, please see license.txt

import frappe
import json
import os
import re
import datetime
import sys
import urllib.request
import urllib.parse


def perform_bootstrap_secrets_handshake():
    """
    Performs secure single-use bootstrap handshake.
    Exchanges the transient ROKCT_BOOTSTRAP_TOKEN for AI credentials,
    loads them strictly in-memory, and immediately deletes the token.
    """
    token = os.environ.get("ROKCT_BOOTSTRAP_TOKEN")
    if not token:
        return

    # Check if already completed to avoid repeated network calls
    if frappe.cache().get_value("bootstrap_completed"):
        os.environ.pop("ROKCT_BOOTSTRAP_TOKEN", None)
        return

    control_url = os.environ.get("ROKCT_CONTROL_URL") or "https://platform.rokct.ai"
    target_endpoint = f"{control_url}/api/method/control.control.bootstrap.get_bootstrap_secrets"

    try:
        data = urllib.parse.urlencode({"token": token}).encode("utf-8")
        req = urllib.request.Request(
            target_endpoint,
            data=data,
            headers={
                "User-Agent": "ROKCT-Bootstrap-Agent/1.0",
                "Content-Type": "application/x-www-form-urlencoded"
            }
        )
        
        with urllib.request.urlopen(req, timeout=10) as response:
            res_data = json.loads(response.read().decode("utf-8"))
            secrets = res_data.get("message")
            
            if secrets:
                # Load keys strictly in-memory in environment & site config
                if secrets.get("gemini_api_key"):
                    os.environ["GEMINI_API_KEY"] = secrets["gemini_api_key"]
                    frappe.local.conf.gemini_api_key = secrets["gemini_api_key"]
                if secrets.get("openai_api_key"):
                    os.environ["OPENAI_API_KEY"] = secrets["openai_api_key"]
                    frappe.local.conf.openai_api_key = secrets["openai_api_key"]
                if secrets.get("whatsapp_bridge_url"):
                    os.environ["WHATSAPP_BRIDGE_URL"] = secrets["whatsapp_bridge_url"]
                    frappe.local.conf.whatsapp_bridge_url = secrets["whatsapp_bridge_url"]
                if secrets.get("tenant_id"):
                    os.environ["TENANT_ID"] = secrets["tenant_id"]
                    frappe.local.conf.tenant_id = secrets["tenant_id"]

                # Auto-initialize ROK configuration files so ROK is instantly pre-configured out of the box
                try:
                    import pathlib
                    rok_home = pathlib.Path.home() / ".rok"
                    rok_home.mkdir(parents=True, exist_ok=True)

                    # 1. Write secure ~/.rok/.env (API Keys)
                    env_file = rok_home / ".env"
                    env_lines = []
                    if secrets.get("gemini_api_key"):
                        env_lines.append(f"GEMINI_API_KEY={secrets['gemini_api_key']}")
                        env_lines.append(f"GOOGLE_API_KEY={secrets['gemini_api_key']}")
                    if secrets.get("openai_api_key"):
                        env_lines.append(f"OPENAI_API_KEY={secrets['openai_api_key']}")
                    if secrets.get("whatsapp_bridge_url"):
                        env_lines.append(f"WHATSAPP_BRIDGE_URL={secrets['whatsapp_bridge_url']}")
                    
                    with open(env_file, "w", encoding="utf-8") as f:
                        f.write("\n".join(env_lines) + "\n")
                    env_file.chmod(0o600)

                    # 2. Write ~/.rok/config.yaml (Default Model and Provider)
                    config_file = rok_home / "config.yaml"
                    if not config_file.exists():
                        # Read available models dynamically from backend models.json SSOT
                        models_config = {}
                        models_file = os.path.join(os.path.dirname(__file__), "models.json")
                        if os.path.exists(models_file):
                            try:
                                with open(models_file, "r", encoding="utf-8") as f:
                                    models_config = json.load(f)
                            except Exception:
                                pass

                        raw_model_id = models_config.get("PAID", {}).get("id", "gemini-3-pro")
                        default_model = f"google/{raw_model_id}" if "gemini" in raw_model_id else raw_model_id
                        
                        config_content = f"""# Automatically generated by ROKCT Bootstrap Handshake
model: "{default_model}"
providers: {{}}
agent:
  max_turns: 90
terminal:
  backend: local
"""
                        with open(config_file, "w", encoding="utf-8") as f:
                            f.write(config_content)
                        config_file.chmod(0o600)
                except Exception as ex:
                    frappe.log_error(f"ROKCT ROK Auto-Config seeding failed: {str(ex)}", "Bootstrap Security")

                frappe.cache().set_value("bootstrap_completed", 1)
                
    except Exception as e:
        frappe.log_error(f"ROKCT Bootstrap handshake failed: {str(e)}", "Bootstrap Security")
    finally:
        # Strictly purge transient token from process memory space
        os.environ.pop("ROKCT_BOOTSTRAP_TOKEN", None)


def ensure_startup_os_core():
    """
    Ensures that the compiler.py and parser.py are available for the plan builder API.
    Resolves the StartupOS path dynamically. Always uses the site-specific StartupOS folder
    to ensure clean isolation and prevent workspace cluttering. If files are missing, 
    fetches them from raw GitHub.
    """
    # Trigger bootstrap secrets handshake first to hydrate API keys in-memory
    perform_bootstrap_secrets_handshake()

    # Always use the site-specific StartupOS directory for clean multi-tenant isolation
    startup_os_root = frappe.get_site_path("StartupOS")

    core_dir = os.path.join(startup_os_root, "core")
    os.makedirs(core_dir, exist_ok=True)

    init_py = os.path.join(core_dir, "__init__.py")
    if not os.path.exists(init_py):
        with open(init_py, 'w') as f:
            f.write("")

    core_files = ["compiler.py", "parser.py", "agent_bridge.py"]

    for f_name in core_files:
        dest_file = os.path.join(core_dir, f_name)
        
        # If the file already exists locally, keep it (do not auto-fetch or overwrite)
        if os.path.exists(dest_file):
            continue

        # Determine if we are in Docker or building the ecosystem
        is_in_docker = os.path.exists("/.dockerenv") or os.path.isdir("/home/frappe/frappe-bench/sites") or os.environ.get("ROKCT_ECOSYSTEM_BUILD")
        in_test = frappe.flags.in_test or os.environ.get("FRAPPE_TEST")

        # 1. Attempt to resolve locally by traversing up out of the current repository (Desktop Sibling Dev check)
        resolved = False
        if not (in_test and not is_in_docker):
            parent = os.path.dirname(os.path.abspath(__file__))
            for _ in range(7):
                parent = os.path.dirname(parent)
                probe_path = os.path.join(parent, "The-Rokct-Protocol", "core", "skills", "startup_os", "scripts", "core", f_name)
                if os.path.exists(probe_path):
                    import shutil
                    shutil.copy(probe_path, dest_file)
                    resolved = True
                    print(f"[StartupOS] Resolved and loaded local core module: {f_name}")
                    break
        
        # 2. If missing (e.g. running in isolated production Docker without submodules), fetch remotely from raw GitHub
        if not resolved and not (in_test and not is_in_docker):
            try:
                print(f"[StartupOS] Attempting remote fetch for {f_name}...")
                github_url = f"https://raw.githubusercontent.com/RokctAI/The-Rokct-Protocol/main/core/skills/startup_os/scripts/core/{f_name}"
                req = urllib.request.Request(
                    github_url,
                    headers={"User-Agent": "ROKCT-Bootstrap-Agent/1.0"}
                )
                with urllib.request.urlopen(req, timeout=10) as response:
                    with open(dest_file, "wb") as out_f:
                        out_f.write(response.read())
                resolved = True
                print(f"[StartupOS] Successfully fetched remote core module: {f_name}")
            except Exception as net_e:
                print(f"[StartupOS] Remote fetch failed for {f_name}: {net_e}")

        # 3. Last resort fallback to test mock if in test mode
        if not resolved:
            if frappe.flags.in_test or os.environ.get("FRAPPE_TEST"):
                with open(dest_file, "w", encoding="utf-8") as f:
                    if f_name == "compiler.py":
                        f.write("def compile_instance(profile_type, instance_name):\n    pass\n")
                    elif f_name == "parser.py":
                        f.write("def parse_questions_md(questions_path):\n    return {}\n")
                    else:
                        f.write("")
                resolved = True
                print(f"[StartupOS] Created test stub for missing module: {f_name}")
            else:
                raise RuntimeError(
                    f"Failed to load StartupOS core engine {f_name}. "
                    "File is missing locally and remote fetching is offline/unavailable."
                )

    if startup_os_root not in sys.path:
        sys.path.insert(0, startup_os_root)

    return startup_os_root


@frappe.whitelist()
def commit_onboarding_answers(profile_type, instance_name, answers, milestones=None):
    """
    Creates or updates the questions.md file for the given profile and instance name,
    runs the StartupOS compiler to render downstream deliverables, and commits
    the resulting plan to the database.
    """
    try:
        if profile_type not in ["business", "life"]:
            frappe.throw("Profile type must be 'business' or 'life'.")

        if not instance_name:
            frappe.throw("Instance name is required.")

        # Ensure core engines are loaded dynamically
        startup_os_root = ensure_startup_os_core()
        
        from core.compiler import compile_instance

        # Handle answers payload (deserialize if string)
        if isinstance(answers, str):
            answers = json.loads(answers)
        if milestones and isinstance(milestones, str):
            milestones = json.loads(milestones)

        # 1. Determine instance folder and write questions.md
        instance_dir = os.path.join(startup_os_root, "instances", profile_type, instance_name)
        os.makedirs(instance_dir, exist_ok=True)
        questions_path = os.path.join(instance_dir, "questions.md")

        # Human-friendly trading name
        display_name = re.sub(r'(?<=[a-z])(?=[A-Z])', ' ', instance_name).strip()

        if profile_type == "business":
            trading_name = answers.get("trading_name") or display_name
            primary_base = answers.get("primary_base") or "Cape Town, South Africa"
            core_value_proposition = answers.get("core_value_proposition") or "Pending — dynamic values."
            customer_segments = answers.get("customer_segments") or "Pending."
            power_strategy = answers.get("power_continuity_strategy") or "Off-grid solar."
            y1 = answers.get("projected_year_1") or "Pending Year 1 projection."
            y2 = answers.get("projected_year_2") or "Pending Year 2 projection."
            y3 = answers.get("projected_year_3") or "Pending Year 3 projection."

            content = f"""# Business Strategic Questions: {trading_name}

This file is the Single Source of Truth (SSOT) for {trading_name}'s strategic, operational, and compliance variables.

---

## 1. Venture Identity & Foundations
*   **Trading Name**: What is the primary commercial brand or trading name?
    *   **Answer**: {trading_name}
*   **Primary Base**: What is your primary geographical base of operations?
    *   **Answer**: {primary_base}
*   **Core Value Proposition**: What is your product or service's unique value statement?
    *   **Answer**: {core_value_proposition}
*   **Customer Segments**: Who are the primary target users and demographic segments?
    *   **Answer**: {customer_segments}

---

## 2. Operations & Power Resilience
*   **Power Continuity Strategy**: How does your venture manage regional load shedding or grid failure?
    *   **Answer**: {power_strategy}

---

## 3. Financial Projections
*   **Projected Year 1**: What is the target Year 1 revenue and profit projection?
    *   **Answer**: {y1}
*   **Projected Year 2**: What is the target Year 2 revenue and profit projection?
    *   **Answer**: {y2}
*   **Projected Year 3**: What is the target Year 3 revenue and profit projection?
    *   **Answer**: {y3}
"""
        else:
            # life
            full_name = answers.get("full_name") or display_name
            gender = answers.get("gender") or "Male"
            primary_base = answers.get("primary_base") or "Cape Town, South Africa"
            life_purpose = answers.get("life_purpose") or "Pending purpose."
            wellness = answers.get("wellness_focus") or "Restore daily sleep depth."
            relationships = answers.get("key_relationships") or "Immediate family."
            legacy = answers.get("legacy_vision") or "Establish a generational legacy."
            ownership = answers.get("business_ownership") or "Pending."

            content = f"""# Life Strategic Questions: {full_name}

This file is the Single Source of Truth (SSOT) for {full_name}'s life development and tactical growth variables.

---

## 1. Personal Identity & Focus
*   **Full Name**: What is your full name?
    *   **Answer**: {full_name}
*   **Gender**: What is your gender?
    *   **Answer**: {gender}
*   **Primary Base**: What is your primary geographical base of operations?
    *   **Answer**: {primary_base}
*   **Life Purpose**: What is your high-level core mission or purpose statement?
    *   **Answer**: {life_purpose}
*   **Wellness Focus**: What is your primary wellness or biological high-performance goal?
    *   **Answer**: {wellness}

---

## 2. Relationships & Stewardship
*   **Key Relationships**: Who are the primary partners, confidants, or trustees in your life?
    *   **Answer**: {relationships}
*   **Legacy Vision**: What is the key long-term stewardship goal?
    *   **Answer**: {legacy}

---

## 3. Venture & Career Integration
*   **Business Ownership**: Do you own a registered business or run a side hustle?
    *   **Answer**: {ownership}
"""

        # Append milestones if provided
        if milestones:
            content += "\n\n## 4. Conversational Milestone Log (Living Ledger)\n"
            for m in milestones:
                m_date = m.get("date") or datetime.date.today().strftime("%Y-%m-%d")
                m_category = m.get("category") or "General"
                m_text = m.get("text") or ""
                if m_text:
                    content += f"\n*   **[{m_date}] ({m_category})**: {m_text}"

        with open(questions_path, 'w', encoding='utf-8') as f:
            f.write(content)

        # 2. Trigger the dynamic compiler
        compile_instance(profile_type, instance_name)

        # 3. Save to database using type-aware commit_plan
        db_result = commit_plan(profile_type=profile_type, instance_name=instance_name)

        # 4. Mark onboarding complete for the Company / site
        try:
            companies = frappe.get_all("Company", limit_page_length=1)
            if companies:
                frappe.db.set_value("Company", companies[0].name, "onboarding_complete", 1)
                frappe.db.commit()
        except Exception as e:
            frappe.log_error(f"Failed to set onboarding_complete: {e}")

        return {
            "status": "success",
            "message": "Questions committed, compiled, and database plan updated successfully.",
            "db_result": db_result
        }

    except Exception as e:
        frappe.log_error(frappe.get_traceback(), "commit_onboarding_answers Error")
        return {"status": "error", "message": str(e)}


@frappe.whitelist()
def generate_alive_cv_pdf(instance_name, profile_type="life", role_focus=None):
    """
    Dynamically parses professional historical milestones from the Single Source of Truth (questions.md)
    and compiles a beautifully formatted, premium CV/Resume PDF on-demand, customized for a specific role focus.
    """
    try:
        startup_os_root = ensure_startup_os_core()
        instance_dir = os.path.join(startup_os_root, "instances", profile_type, instance_name)
        questions_path = os.path.join(instance_dir, "questions.md")

        if not os.path.exists(questions_path):
            frappe.throw(f"Active strategic profile '{instance_name}' not found under {profile_type}.")

        # Parse main profile attributes from questions.md
        with open(questions_path, "r", encoding="utf-8") as f:
            q_content = f.read()

        full_name_match = re.search(r'# (?:Business Strategic Questions|Life Strategic Questions): (.*)', q_content)
        full_name = full_name_match.group(1) if full_name_match else instance_name
        
        primary_base_match = re.search(r'\*\s+\*\*Primary Base\*\*:[^*]*\*\s+\*\*Answer\*\*:\s*(.*)', q_content)
        primary_base = primary_base_match.group(1) if primary_base_match else "Cape Town, South Africa"

        life_purpose_match = re.search(r'\*\s+\*\*Life Purpose\*\*:[^*]*\*\s+\*\*Answer\*\*:\s*(.*)', q_content)
        life_purpose = life_purpose_match.group(1) if life_purpose_match else ""

        # Parse milestones
        milestones = []
        in_milestones = False
        for line in q_content.splitlines():
            if "## 4. Conversational Milestone Log" in line:
                in_milestones = True
                continue
            if in_milestones:
                # Format: *   **[2026-05-26] (Category)**: Text
                match = re.match(r'^\*\s+\*\*\[([^\]]+)\]\s+\(([^\)]+)\)\*\*:\s*(.*)$', line.strip())
                if match:
                    milestones.append({
                        "date": match.group(1),
                        "category": match.group(2),
                        "text": match.group(3)
                    })

        # Apply LLM Role Customization if requested and key is present
        summary_intro = life_purpose
        if role_focus and (os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_API_KEY")):
            try:
                # Use Completions to optimize the introductory profile for the target role focus
                system_prompt = "You are a professional CV Optimizer. Rewrite the user's career/life summary to dynamically align with the requested target role focus. Keep it concise (max 3 sentences)."
                user_content = f"Name: {full_name}\nOriginal summary: {life_purpose}\nTarget Role Focus: {role_focus}"
                
                # Dynamic completion via ROK completions endpoint
                import requests
                import os
                url = os.environ.get("ROK_COMPLETIONS_URL") or "http://127.0.0.1:8642/v1/chat/completions"
                payload = {
                    "model": "hermes-agent",
                    "messages": [
                        {"role": "system", "content": system_prompt},
                        {"role": "user", "content": user_content}
                    ],
                    "stream": False
                }
                res = requests.post(url, json=payload, headers={"Content-Type": "application/json"}, timeout=15.0)
                if res.ok:
                    choices = res.json().get("choices", [])
                    if choices:
                        summary_intro = choices[0].get("message", {}).get("content", "").strip()
            except Exception as e:
                frappe.log_error(f"Failed to dynamically tailor CV for {role_focus}: {e}")

        # Build Premium HTML template with harmonious styling (HSL, Inter Font, premium colors)
        milestones_html = ""
        for m in milestones:
            milestones_html += f"""
            <div class="timeline-item">
                <div class="timeline-date">{m['date']}</div>
                <div class="timeline-marker"></div>
                <div class="timeline-content">
                    <span class="timeline-category">{m['category']}</span>
                    <p class="timeline-text">{m['text']}</p>
                </div>
            </div>
            """

        if not milestones_html:
            milestones_html = "<p class='no-milestones'>No career or personal milestones logged yet. Share milestones ambiently with Rok!</p>"

        role_badge = f"<span class='role-focus-badge'>{role_focus} Focus</span>" if role_focus else ""

        html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="utf-8">
            <title>Alive CV - {full_name}</title>
            <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600;800&display=swap" rel="stylesheet">
            <style>
                body {{
                    font-family: 'Outfit', sans-serif;
                    color: #1e293b;
                    background-color: #ffffff;
                    margin: 0;
                    padding: 40px;
                    line-height: 1.6;
                }}
                .header {{
                    border-bottom: 2px solid #e2e8f0;
                    padding-bottom: 24px;
                    margin-bottom: 30px;
                    position: relative;
                }}
                .name {{
                    font-size: 36px;
                    font-weight: 800;
                    color: #0f172a;
                    margin: 0;
                    letter-spacing: -0.5px;
                }}
                .base {{
                    font-size: 14px;
                    color: #64748b;
                    font-weight: 600;
                    margin-top: 4px;
                }}
                .role-focus-badge {{
                    position: absolute;
                    top: 10px;
                    right: 0;
                    background-color: #6366f1;
                    color: #ffffff;
                    font-size: 12px;
                    font-weight: 600;
                    padding: 6px 14px;
                    border-radius: 9999px;
                    text-transform: uppercase;
                    letter-spacing: 0.5px;
                }}
                .section {{
                    margin-bottom: 35px;
                }}
                .section-title {{
                    font-size: 18px;
                    font-weight: 600;
                    color: #4f46e5;
                    border-bottom: 1px solid #f1f5f9;
                    padding-bottom: 8px;
                    margin-bottom: 20px;
                    text-transform: uppercase;
                    letter-spacing: 1px;
                }}
                .summary {{
                    font-size: 15px;
                    color: #334155;
                    margin: 0;
                }}
                .timeline {{
                    position: relative;
                    padding-left: 24px;
                }}
                .timeline::before {{
                    content: '';
                    position: absolute;
                    left: 4px;
                    top: 5px;
                    bottom: 5px;
                    width: 2px;
                    background-color: #e2e8f0;
                }}
                .timeline-item {{
                    position: relative;
                    margin-bottom: 24px;
                }}
                .timeline-date {{
                    font-size: 13px;
                    font-weight: 600;
                    color: #6366f1;
                    margin-bottom: 4px;
                }}
                .timeline-marker {{
                    position: absolute;
                    left: -24px;
                    top: 4px;
                    width: 10px;
                    height: 10px;
                    border-radius: 50%;
                    background-color: #ffffff;
                    border: 2px solid #6366f1;
                }}
                .timeline-content {{
                    background: #f8fafc;
                    border: 1px solid #f1f5f9;
                    border-radius: 8px;
                    padding: 14px 18px;
                }}
                .timeline-category {{
                    display: inline-block;
                    font-size: 10px;
                    font-weight: 600;
                    color: #475569;
                    background-color: #cbd5e1;
                    padding: 2px 8px;
                    border-radius: 4px;
                    margin-bottom: 6px;
                    text-transform: uppercase;
                }}
                .timeline-text {{
                    font-size: 14px;
                    color: #334155;
                    margin: 0;
                }}
                .no-milestones {{
                    color: #64748b;
                    font-style: italic;
                    font-size: 14px;
                }}
            </style>
        </head>
        <body>
            <div class="header">
                <h1 class="name">{full_name}</h1>
                <div class="base">📍 {primary_base}</div>
                {role_badge}
            </div>

            <div class="section">
                <h2 class="section-title">Professional Executive Summary</h2>
                <p class="summary">{summary_intro}</p>
            </div>

            <div class="section">
                <h2 class="section-title">Milestones & Achievements Ledger</h2>
                <div class="timeline">
                    {milestones_html}
                </div>
            </div>
        </body>
        </html>
        """

        # Compile HTML string to pristine PDF binary
        from frappe.utils.pdf import get_pdf
        pdf_bytes = get_pdf(html)

        # Deliver as dynamic file attachment
        frappe.local.response.filename = f"Alive_CV_{instance_name}.pdf"
        frappe.local.response.filecontent = pdf_bytes
        frappe.local.response.type = "download"

    except Exception as e:
        frappe.log_error(frappe.get_traceback(), "generate_alive_cv_pdf Error")
        frappe.throw(f"Failed to generate dynamic CV PDF: {e}")


@frappe.whitelist()
def generate_strategic_alignment_report(instance_name, profile_type="life"):
    """
    Acts as the dynamic Orchestrator. Queries the live database (operational task/goal telemetry)
    and compares it to the questions.md strategic baseline (SSOT), invoking ROK completions
    to compile a premium Strategic Alignment & Accountability Report.
    """
    try:
        startup_os_root = ensure_startup_os_core()
        instance_dir = os.path.join(startup_os_root, "instances", profile_type, instance_name)
        questions_path = os.path.join(instance_dir, "questions.md")

        if not os.path.exists(questions_path):
            frappe.throw(f"Active strategic baseline questions.md not found for '{instance_name}'.")

        # 1. Read the Strategic Baseline (SSOT)
        with open(questions_path, "r", encoding="utf-8") as f:
            baseline_md = f.read()

        # 2. Gather Operational Telemetry from Database
        db_telemetry = {
            "visions": [],
            "pillars": [],
            "objectives": [],
            "kpis": [],
            "personal_goals": [],
            "completed_milestones": 0
        }

        # Query Vision
        try:
            visions = frappe.get_all("Vision", filters={"title": ["like", f"%{instance_name}%"]}, fields=["name", "title", "description"])
            db_telemetry["visions"] = visions
            if visions:
                v_name = visions[0]["name"]
                # Query Pillars
                pillars = frappe.get_all("Pillar", filters={"parent_vision": v_name}, fields=["name", "title", "description"])
                db_telemetry["pillars"] = pillars
                
                # Query Objectives & KPIs
                for p in pillars:
                    objs = frappe.get_all("Strategic Objective", filters={"pillar": p["name"]}, fields=["name", "title", "description", "status"])
                    db_telemetry["objectives"].extend(objs)
                    for o in objs:
                        kpis = frappe.get_all("KPI", filters={"objective": o["name"]}, fields=["name", "title", "target_value", "current_value"])
                        db_telemetry["kpis"].extend(kpis)
        except Exception as db_err:
            # Fallback gracefully if DocTypes are not fully loaded in standard test mock run
            frappe.log_error(f"Strategic DB queries skipped or partially failed: {db_err}")

        # Query Personal Mastery Goals (Life Profile Specific)
        if profile_type == "life":
            try:
                goals = frappe.get_all("Personal Mastery Goal", fields=["name", "title", "status", "weekly_check_in"])
                db_telemetry["personal_goals"] = goals
            except Exception:
                pass

        return {
            "status": "success",
            "instance_name": instance_name,
            "profile_type": profile_type,
            "baseline_strategy": baseline_md,
            "live_database_telemetry": db_telemetry,
            "db_telemetry_summary": {
                "active_pillars": len(db_telemetry["pillars"]),
                "tracked_objectives": len(db_telemetry["objectives"]),
                "active_kpis": len(db_telemetry["kpis"]),
                "personal_goals": len(db_telemetry["personal_goals"])
            }
        }

    except Exception as e:
        frappe.log_error(frappe.get_traceback(), "generate_strategic_alignment_report Error")
        return {"status": "error", "message": str(e)}


@frappe.whitelist()
def commit_plan(plan_data=None, profile_type=None, instance_name=None):
    """
    Accepts either raw JSON payload from frontend (backward compatibility)
    or profile_type + instance_name to parse compiled strategic markdown deliverables
    and seed them directly to the database, ensuring files stop being used for operational work.
    """
    try:
        # Determine standard StartupOS paths and imports
        startup_os_root = ensure_startup_os_core()
        from core.parser import parse_questions_md

        # 1. Clear existing plan if any to avoid duplication
        plan_doc = frappe.get_doc("Plan On A Page")
        if plan_doc.vision:
            old_vision = plan_doc.vision
            # Delete old KPIs, Objectives, and Pillars linked to this Vision
            pillars = frappe.get_all("Pillar", filters={"vision": old_vision})
            for p in pillars:
                objectives = frappe.get_all("Strategic Objective", filters={"pillar": p.name})
                for o in objectives:
                    frappe.db.delete("KPI", {"strategic_objective": o.name})
                frappe.db.delete("Strategic Objective", {"pillar": p.name})
            frappe.db.delete("Pillar", {"vision": old_vision})
            frappe.db.delete("Vision", {"name": old_vision})
            
            plan_doc.vision = None
            plan_doc.save(ignore_permissions=True)

        # 2. Case A: Raw plan_data passed (backward compatibility)
        if plan_data:
            data = json.loads(plan_data)
            
            # Create the Vision
            vision_doc = frappe.new_doc("Vision")
            vision_doc.title = data.get("vision_title")
            vision_doc.description = data.get("vision_description")
            vision_doc.insert(ignore_permissions=True)

            # Create Pillars, Objectives, KPIs
            for pillar_data in data.get("pillars", []):
                pillar_doc = frappe.new_doc("Pillar")
                pillar_doc.title = pillar_data.get("title")
                pillar_doc.description = pillar_data.get("description")
                pillar_doc.vision = vision_doc.name
                pillar_doc.insert(ignore_permissions=True)

                for objective_data in pillar_data.get("objectives", []):
                    objective_doc = frappe.new_doc("Strategic Objective")
                    objective_doc.title = objective_data.get("title")
                    objective_doc.description = objective_data.get("description")
                    objective_doc.pillar = pillar_doc.name
                    objective_doc.insert(ignore_permissions=True)

                    for kpi_data in objective_data.get("kpis", []):
                        kpi_doc = frappe.new_doc("KPI")
                        kpi_doc.title = kpi_data.get("title")
                        kpi_doc.description = kpi_data.get("description")
                        kpi_doc.strategic_objective = objective_doc.name
                        kpi_doc.insert(ignore_permissions=True)

            plan_doc.vision = vision_doc.name
            plan_doc.save(ignore_permissions=True)
            return {"status": "success", "message": "Plan on a Page created successfully."}

        # 3. Case B: Profile type and instance name passed (read and parse compiled output files)
        if not profile_type or not instance_name:
            frappe.throw("Invalid arguments. Must supply either plan_data or profile_type + instance_name.")

        output_dir = os.path.join(startup_os_root, "instances", profile_type, instance_name, "output")
        
        has_compiled_files = False
        parsed_plans = []

        # Local markdown parser function
        def parse_compiled_markdown(file_path):
            with open(file_path, "r", encoding="utf-8") as f:
                content = f.read()

            # Strip footers and metadata blocks
            content_clean = re.split(r"## Strategic Document Mappings", content, flags=re.IGNORECASE)[0]
            content_clean = re.sub(r">\s*\[!IMPORTANT\]\s*\n\s*>\s*\*\*Document Version Control\*\*.*?\n\n", "", content_clean, flags=re.DOTALL | re.IGNORECASE)
            content_clean = content_clean.replace("---", "")

            lines = content_clean.split("\n")
            parsed_data = {
                "title": "",
                "description": "",
                "pillars": []
            }
            
            current_pillar = None
            current_objective = None
            description_lines = []
            in_h1_intro = False
            
            for line in lines:
                line_strip = line.strip()
                if not line_strip:
                    continue
                    
                if line_strip.startswith("# "):
                    parsed_data["title"] = line_strip[2:].strip()
                    in_h1_intro = True
                    continue
                    
                if line_strip.startswith("## "):
                    in_h1_intro = False
                    p_title = line_strip[3:].strip()
                    p_title = re.sub(r"^\d+[\.\s\-]+", "", p_title)
                    current_pillar = {
                        "title": p_title,
                        "description": "",
                        "objectives": []
                    }
                    parsed_data["pillars"].append(current_pillar)
                    current_objective = None
                    continue
                    
                if line_strip.startswith("### "):
                    in_h1_intro = False
                    if not current_pillar:
                        current_pillar = {
                            "title": "General",
                            "description": "",
                            "objectives": []
                        }
                        parsed_data["pillars"].append(current_pillar)
                    
                    obj_title = line_strip[4:].strip()
                    obj_title = re.sub(r"^[A-Z0-9]+[\.\s\-]+", "", obj_title)
                    current_objective = {
                        "title": obj_title,
                        "description": "",
                        "kpis": []
                    }
                    current_pillar["objectives"].append(current_objective)
                    continue
                    
                if line_strip.startswith(("* ", "- ", "1. ", "2. ", "3. ", "4. ", "5. ")):
                    in_h1_intro = False
                    bullet_content = re.sub(r"^(\*\s*|-\s*|\d+[\.\s\-]+)", "", line_strip).strip()
                    
                    if ":" in bullet_content:
                        b_title, b_val = bullet_content.split(":", 1)
                        b_title = b_title.strip()
                        b_val = b_val.strip()
                    else:
                        b_title = bullet_content
                        b_val = bullet_content
                        
                    if current_objective:
                        current_objective["kpis"].append({
                            "title": b_title,
                            "description": b_val
                        })
                    else:
                        if not current_pillar:
                            current_pillar = {
                                "title": "General",
                                "description": "",
                                "objectives": []
                            }
                            parsed_data["pillars"].append(current_pillar)
                        
                        obj = {
                            "title": b_title,
                            "description": b_val,
                            "kpis": []
                        }
                        current_pillar["objectives"].append(obj)
                    continue
                    
                if in_h1_intro:
                    description_lines.append(line_strip)
                elif current_objective:
                    current_objective["description"] = (current_objective["description"] + "\n" + line_strip).strip()
                elif current_pillar:
                    current_pillar["description"] = (current_pillar["description"] + "\n" + line_strip).strip()

            if description_lines:
                parsed_data["description"] = "\n".join(description_lines)
                
            return parsed_data

        if os.path.exists(output_dir):
            import glob
            md_files = glob.glob(os.path.join(output_dir, "*.md"))
            # Filter out narratives/resumes (cv.md and obituary.md)
            strategic_files = [f for f in md_files if os.path.basename(f) not in ["cv.md", "obituary.md"]]
            
            if strategic_files:
                has_compiled_files = True
                for f_path in strategic_files:
                    try:
                        plan = parse_compiled_markdown(f_path)
                        if plan["title"] or plan["pillars"]:
                            parsed_plans.append(plan)
                    except Exception as parse_err:
                        frappe.log_error(f"Failed to parse compiled strategic file {f_path}: {parse_err}")

        # Seeding Vision, Pillars, Objectives, KPIs
        vision_doc = None
        if has_compiled_files and parsed_plans:
            # 1. Establish central Vision DocType from primary plan
            primary_plan = parsed_plans[0]
            for p in parsed_plans:
                if "plan_on_a_page" in p["title"].lower() or "plan on a page" in p["title"].lower():
                    primary_plan = p
                    break
            
            vision_doc = frappe.new_doc("Vision")
            vision_doc.title = primary_plan["title"]
            vision_doc.description = primary_plan["description"] or f"Strategic Plan on a Page for {instance_name}"
            vision_doc.insert(ignore_permissions=True)

            # 2. Iterate and feed all parsed strategic files directly as DB Seed
            for plan in parsed_plans:
                for pillar_data in plan["pillars"]:
                    # Create Pillar
                    pillar_doc = frappe.new_doc("Pillar")
                    pillar_doc.title = pillar_data["title"]
                    pillar_doc.description = pillar_data["description"] or f"Strategic pillar for {plan['title']}"
                    pillar_doc.vision = vision_doc.name
                    pillar_doc.insert(ignore_permissions=True)

                    # Create Objectives & KPIs
                    for obj_data in pillar_data["objectives"]:
                        objective_doc = frappe.new_doc("Strategic Objective")
                        objective_doc.title = obj_data["title"]
                        objective_doc.description = obj_data["description"] or f"Objective for {pillar_data['title']}"
                        objective_doc.pillar = pillar_doc.name
                        objective_doc.insert(ignore_permissions=True)

                        for kpi_data in obj_data["kpis"]:
                            kpi_doc = frappe.new_doc("KPI")
                            kpi_doc.title = kpi_data["title"]
                            kpi_doc.description = kpi_data["description"]
                            kpi_doc.strategic_objective = objective_doc.name
                            kpi_doc.insert(ignore_permissions=True)

            # Seed additional custom structures if needed
            if profile_type == "business":
                policy_title = f"{instance_name} Strategic Alignment Policy"
                if not frappe.db.exists("Company Policy", policy_title):
                    policy_doc = frappe.new_doc("Company Policy")
                    policy_doc.title = policy_title
                    policy_doc.description = f"Enterprise-wide mandate generated from compiled strategic business plan deliverables."
                    policy_doc.insert(ignore_permissions=True)
            else:
                goal_title = f"{instance_name}: Wellness Mastery"
                if not frappe.db.exists("Personal Mastery Goal", goal_title):
                    goal_doc = frappe.new_doc("Personal Mastery Goal")
                    goal_doc.title = goal_title
                    goal_doc.description = f"Physical wellness mastery goal compiled from personal life plan."
                    goal_doc.insert(ignore_permissions=True)

        else:
            # Fallback Recovery to questions.md parsed answers (useful for mock/test stubs execution)
            questions_path = os.path.join(startup_os_root, "instances", profile_type, instance_name, "questions.md")
            if not os.path.exists(questions_path):
                frappe.throw(f"StartupOS questions.md not found at: {questions_path}")

            q_data = parse_questions_md(questions_path)
            display_name = re.sub(r'(?<=[a-z])(?=[A-Z])', ' ', instance_name).strip()

            if profile_type == "business":
                trading_name = q_data.get("trading_name") or display_name
                core_val = q_data.get("core_value_proposition") or "Pending core values."
                cust_seg = q_data.get("customer_segments") or "Pending segments."
                power_strategy = q_data.get("power_continuity_strategy") or "Off-grid solar."

                vision_doc = frappe.new_doc("Vision")
                vision_doc.title = f"Vision: {trading_name}"
                vision_doc.description = f"Core Mission: alternative bookkeeping. Value Proposition: {core_val}"
                vision_doc.insert(ignore_permissions=True)

                p1 = frappe.new_doc("Pillar")
                p1.title = "Identity & Customer Foundations"
                p1.description = "Validate customer segments."
                p1.vision = vision_doc.name
                p1.insert(ignore_permissions=True)

                o1 = frappe.new_doc("Strategic Objective")
                o1.title = "Validate Customer Segments"
                o1.description = f"Target segment definition: {cust_seg}"
                o1.pillar = p1.name
                o1.insert(ignore_permissions=True)

                p2 = frappe.new_doc("Pillar")
                p2.title = "Operations & Resilience"
                p2.description = "Resilience framework."
                p2.vision = vision_doc.name
                p2.insert(ignore_permissions=True)

                o2 = frappe.new_doc("Strategic Objective")
                o2.title = "Ensure Power Continuity"
                o2.description = f"Power strategy: {power_strategy}"
                o2.pillar = p2.name
                o2.insert(ignore_permissions=True)

                policy_title = f"{trading_name} Strategic Alignment Policy"
                if not frappe.db.exists("Company Policy", policy_title):
                    policy_doc = frappe.new_doc("Company Policy")
                    policy_doc.title = policy_title
                    policy_doc.description = f"Enterprise-wide mandate to pursue: {core_val}"
                    policy_doc.insert(ignore_permissions=True)

            else:
                full_name = q_data.get("full_name") or display_name
                life_purpose = q_data.get("life_purpose") or "Pending purpose."
                wellness = q_data.get("wellness_focus") or "Restore sleep."

                vision_doc = frappe.new_doc("Vision")
                vision_doc.title = f"Life Purpose: {full_name}"
                vision_doc.description = life_purpose
                vision_doc.insert(ignore_permissions=True)

                p1 = frappe.new_doc("Pillar")
                p1.title = "Personal Identity & Wellness"
                p1.description = "Nurture biological mastery."
                p1.vision = vision_doc.name
                p1.insert(ignore_permissions=True)

                o1 = frappe.new_doc("Strategic Objective")
                o1.title = "Optimize Physical Conditioning"
                o1.description = f"Wellness focus: {wellness}"
                o1.pillar = p1.name
                o1.insert(ignore_permissions=True)

                goal_title = f"{full_name}: Wellness Mastery"
                if not frappe.db.exists("Personal Mastery Goal", goal_title):
                    goal_doc = frappe.new_doc("Personal Mastery Goal")
                    goal_doc.title = goal_title
                    goal_doc.description = f"Physical condition focus: {wellness}"
                    goal_doc.insert(ignore_permissions=True)

        if vision_doc:
            plan_doc.vision = vision_doc.name
            plan_doc.save(ignore_permissions=True)

        return {"status": "success", "message": "Plan on a Page committed and seeded from compiled strategic files successfully."}

    except Exception as e:
        frappe.log_error(frappe.get_traceback(), "commit_plan Error")
        return {"status": "error", "message": str(e)}


@frappe.whitelist()
def chat_with_rok(message, session_id=None, model=None):
    """
    Secure gateway proxy for Next.js (Vercel) to chat with ROK agent on the Tenant VPS.
    """
    try:
        # Check if ROK is enabled for this subscription tier
        from rcore.utils.subscription_checker import get_cached_subscription_details
        sub = get_cached_subscription_details()
        if sub.get("is_free_plan", 0) or not sub.get("is_ai", 0):
            # Enforce 5 free messages daily limit
            user_id = frappe.session.user
            today_date = datetime.date.today().strftime("%Y-%m-%d")
            cache_key = f"free_rok_msg_count:{user_id}:{today_date}"
            current_count = frappe.cache().get_value(cache_key) or 0
            if current_count >= 5:
                frappe.throw(
                    "Quota Exceeded: Your daily free conversational ROK quota is complete! To make sure you don't lose any of the progress we've made, we are switching your Strategic Onboarding to Predefined (Offline) Mode. You can continue answering the remaining questions statically. To reactivate my smart auditing and reasoning right now, upgrade to a Pro plan!",
                    frappe.PermissionError
                )
            frappe.cache().set_value(cache_key, current_count + 1, expires_in_sec=86400)

        # Secure seat assignment and license gatekeeping
        from rcore.tenant.api import get_token_usage
        usage_tracker = get_token_usage()
        if usage_tracker.get("seat_limit_exceeded"):
            frappe.throw(
                "Your team's ROK seat limit has been reached. Please contact your administrator to upgrade your subscription.",
                frappe.PermissionError
            )
        import os
        url = os.environ.get("ROK_COMPLETIONS_URL") or "http://127.0.0.1:8642/v1/chat/completions"
        headers = {
            "Content-Type": "application/json",
        }
        if session_id:
            headers["X-Hermes-Session-Id"] = session_id

        # Securely isolate memory context per user in multi-tenant environment
        user_id = frappe.session.user
        if user_id:
            headers["X-Hermes-User-Id"] = user_id

        payload = {
            "model": model or "hermes-agent",
            "messages": [
                {"role": "user", "content": message}
            ],
            "stream": False
        }

        import requests
        response = requests.post(url, json=payload, headers=headers, timeout=60.0)
        response.raise_for_status()

        result = response.json()
        choices = result.get("choices", [])
        if choices:
            return {
                "status": "success",
                "message": choices[0].get("message", {}).get("content", ""),
                "tool_calls": choices[0].get("message", {}).get("tool_calls", None),
                "session_id": session_id
            }
        return {"status": "error", "message": "No response choice returned from ROK."}

    except Exception as e:
        frappe.log_error(f"ROK Tenant Chat Bridge failed: {e}")
        return {"status": "error", "message": str(e)}


@frappe.whitelist()
def summarize_chat_session(session_id, messages):
    """
    Summarizes a completed or long chat session via the ROK completions loop on Tenant.
    """
    try:
        import os
        url = os.environ.get("ROK_COMPLETIONS_URL") or "http://127.0.0.1:8642/v1/chat/completions"
        headers = {
            "Content-Type": "application/json",
        }
        if session_id:
            headers["X-Hermes-Session-Id"] = session_id

        # Securely isolate memory context per user in multi-tenant environment
        user_id = frappe.session.user
        if user_id:
            headers["X-Hermes-User-Id"] = user_id

        # Decode messages if they are passed as JSON string
        if isinstance(messages, str):
            try:
                import json
                messages = json.loads(messages)
            except Exception:
                pass

        system_prompt = (
            "Provide a concise, high-level summary of the preceding conversation "
            "highlighting the core user goals, preferences, and strategic answers collected. "
            "This summary will serve as the golden thread context for future sessions."
        )

        payload = {
            "model": "hermes-agent",
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": f"Here is the conversation to summarize:\n{json.dumps(messages, indent=2)}"}
            ],
            "stream": False
        }

        import requests
        response = requests.post(url, json=payload, headers=headers, timeout=60.0)
        response.raise_for_status()

        result = response.json()
        choices = result.get("choices", [])
        if choices:
            summary = choices[0].get("message", {}).get("content", "")
            # Save Engram memory if brain app exists
            if frappe.db.exists("DocType", "Engram"):
                engram_name = f"chat-summary-{session_id}"
                if not frappe.db.exists("Engram", engram_name):
                    engram = frappe.new_doc("Engram")
                    engram.reference_doctype = "Chat Session"
                    engram.reference_name = session_id
                    engram.reference_title = f"Chat Session Summary: {session_id}"
                    engram.summary = summary
                    engram.insert(ignore_permissions=True)
                else:
                    engram = frappe.get_doc("Engram", engram_name)
                    engram.summary = summary
                    engram.save(ignore_permissions=True)

            return {
                "status": "success",
                "summary": summary
            }
        return {"status": "error", "message": "No summary choice returned from ROK."}

    except Exception as e:
        frappe.log_error(f"ROK Summarization failed: {e}")
        return {"status": "error", "message": str(e)}



@frappe.whitelist(allow_guest=True)
def get_available_models():
    """
    Returns available AI models configured on the backend (Single Source of Truth)
    """
    models_file = os.path.join(os.path.dirname(__file__), "models.json")
    if os.path.exists(models_file):
        try:
            with open(models_file, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception as e:
            frappe.log_error(f"Failed to read models.json: {str(e)}", "AI Models Configuration")
    return {}


