# Copyright (c) 2026 ROKCT INTELLIGENCE (PTY) LTD
# For license information, please see license.txt

import frappe
import json
import os
import re
import datetime
import sys
import urllib.request
import urllib.parse


def perform_bootstrap_secrets_handshake():
    """
    Performs secure single-use bootstrap handshake.
    Exchanges the transient ROKCT_BOOTSTRAP_TOKEN for AI credentials,
    loads them strictly in-memory, and immediately deletes the token.
    """
    token = os.environ.get("ROKCT_BOOTSTRAP_TOKEN")
    if not token:
        return

    # Check if already completed to avoid repeated network calls
    if frappe.cache().get_value("bootstrap_completed"):
        os.environ.pop("ROKCT_BOOTSTRAP_TOKEN", None)
        return

    control_url = os.environ.get("ROKCT_CONTROL_URL") or "http://172.17.0.1:8000"
    target_endpoint = (
        f"{control_url}/api/method/control.control.bootstrap.get_bootstrap_secrets"
    )

    try:
        data = urllib.parse.urlencode({"token": token}).encode("utf-8")
        req = urllib.request.Request(
            target_endpoint,
            data=data,
            headers={
                "User-Agent": "ROKCT-Bootstrap-Agent/1.0",
                "Content-Type": "application/x-www-form-urlencoded",
            },
        )

        with urllib.request.urlopen(req, timeout=10) as response:
            res_data = json.loads(response.read().decode("utf-8"))
            secrets = res_data.get("message")

            if secrets:
                # Load keys strictly in-memory in environment & site config
                if secrets.get("gemini_api_key"):
                    os.environ["GEMINI_API_KEY"] = secrets["gemini_api_key"]
                    frappe.local.conf.gemini_api_key = secrets["gemini_api_key"]
                if secrets.get("openai_api_key"):
                    os.environ["OPENAI_API_KEY"] = secrets["openai_api_key"]
                    frappe.local.conf.openai_api_key = secrets["openai_api_key"]
                if secrets.get("whatsapp_bridge_url"):
                    os.environ["WHATSAPP_BRIDGE_URL"] = secrets["whatsapp_bridge_url"]
                    frappe.local.conf.whatsapp_bridge_url = secrets[
                        "whatsapp_bridge_url"
                    ]
                if secrets.get("tenant_id"):
                    os.environ["TENANT_ID"] = secrets["tenant_id"]
                    frappe.local.conf.tenant_id = secrets["tenant_id"]

                # Auto-initialize ROK configuration files so ROK is instantly pre-configured out of the box
                try:
                    import pathlib

                    rok_home = pathlib.Path.home() / ".rok"
                    rok_home.mkdir(parents=True, exist_ok=True)

                    # 1. Write secure ~/.rok/.env (API Keys)
                    env_file = rok_home / ".env"
                    env_lines = []
                    if secrets.get("gemini_api_key"):
                        env_lines.append(f"GEMINI_API_KEY={secrets['gemini_api_key']}")
                        env_lines.append(f"GOOGLE_API_KEY={secrets['gemini_api_key']}")
                    if secrets.get("openai_api_key"):
                        env_lines.append(f"OPENAI_API_KEY={secrets['openai_api_key']}")
                    if secrets.get("whatsapp_bridge_url"):
                        env_lines.append(
                            f"WHATSAPP_BRIDGE_URL={secrets['whatsapp_bridge_url']}"
                        )

                    with open(env_file, "w", encoding="utf-8") as f:
                        f.write("\n".join(env_lines) + "\n")
                    env_file.chmod(0o600)

                    # 2. Write ~/.rok/config.yaml (Default Model and Provider)
                    config_file = rok_home / "config.yaml"
                    if not config_file.exists():
                        # Read available models dynamically from backend models.json SSOT
                        models_config = {}
                        models_file = os.path.join(
                            os.path.dirname(__file__), "models.json"
                        )
                        if os.path.exists(models_file):
                            try:
                                with open(models_file, "r", encoding="utf-8") as f:
                                    models_config = json.load(f)
                            except Exception:
                                pass

                        raw_model_id = models_config.get("PAID", {}).get(
                            "id", "gemini-3-pro"
                        )
                        default_model = (
                            f"google/{raw_model_id}"
                            if "gemini" in raw_model_id
                            else raw_model_id
                        )

                        config_content = f"""# Automatically generated by ROKCT Bootstrap Handshake
model: "{default_model}"
providers: {{}}
agent:
  max_turns: 90
terminal:
  backend: local
"""
                        with open(config_file, "w", encoding="utf-8") as f:
                            f.write(config_content)
                        config_file.chmod(0o600)
                except Exception as ex:
                    frappe.log_error(
                        f"ROKCT ROK Auto-Config seeding failed: {str(ex)}",
                        "Bootstrap Security",
                    )

                frappe.cache().set_value("bootstrap_completed", 1)

    except Exception as e:
        frappe.log_error(
            f"ROKCT Bootstrap handshake failed: {str(e)}", "Bootstrap Security"
        )
    finally:
        # Strictly purge transient token from process memory space
        os.environ.pop("ROKCT_BOOTSTRAP_TOKEN", None)


def ensure_startup_os_core():
    """
    Ensures that the compiler.py and parser.py are available for the plan builder API.
    Resolves the StartupOS path dynamically. Always uses the site-specific StartupOS folder
    to ensure clean isolation and prevent workspace cluttering. If files are missing,
    fetches them from raw GitHub.
    """
    # Trigger bootstrap secrets handshake first to hydrate API keys in-memory
    perform_bootstrap_secrets_handshake()

    # Always use the site-specific StartupOS directory for clean multi-tenant isolation
    startup_os_root = frappe.get_site_path("StartupOS")

    core_dir = os.path.join(startup_os_root, "core")
    os.makedirs(core_dir, exist_ok=True)

    init_py = os.path.join(core_dir, "__init__.py")
    if not os.path.exists(init_py):
        with open(init_py, "w") as f:
            f.write("")

    core_files = ["compiler.py", "parser.py", "agent_bridge.py"]

    for f_name in core_files:
        dest_file = os.path.join(core_dir, f_name)

        # If the file already exists locally, keep it (do not auto-fetch or overwrite)
        if os.path.exists(dest_file):
            continue

        # Determine if we are in Docker or building the ecosystem
        is_in_docker = (
            os.path.exists("/.dockerenv")
            or os.path.isdir("/home/frappe/frappe-bench/sites")
            or os.environ.get("ROKCT_ECOSYSTEM_BUILD")
        )
        in_test = frappe.flags.in_test or os.environ.get("FRAPPE_TEST")

        # 1. Attempt to resolve locally by traversing up out of the current repository (Desktop Sibling Dev check)
        resolved = False
        if not (in_test and not is_in_docker):
            parent = os.path.dirname(os.path.abspath(__file__))
            for _ in range(7):
                parent = os.path.dirname(parent)
                probe_path = os.path.join(
                    parent,
                    "The-Rokct-Protocol",
                    "core",
                    "skills",
                    "startup_os",
                    "scripts",
                    "core",
                    f_name,
                )
                if os.path.exists(probe_path):
                    import shutil

                    shutil.copy(probe_path, dest_file)
                    resolved = True
                    print(
                        f"[StartupOS] Resolved and loaded local core module: {f_name}"
                    )
                    break

        # 2. If missing (e.g. running in isolated production Docker without submodules), fetch remotely from raw GitHub
        if not resolved and not (in_test and not is_in_docker):
            try:
                print(f"[StartupOS] Attempting remote fetch for {f_name}...")
                github_url = f"https://raw.githubusercontent.com/RokctAI/The-Rokct-Protocol/main/core/skills/startup_os/scripts/core/{f_name}"
                req = urllib.request.Request(
                    github_url, headers={"User-Agent": "ROKCT-Bootstrap-Agent/1.0"}
                )
                with urllib.request.urlopen(req, timeout=10) as response:
                    with open(dest_file, "wb") as out_f:
                        out_f.write(response.read())
                resolved = True
                print(f"[StartupOS] Successfully fetched remote core module: {f_name}")
            except Exception as net_e:
                print(f"[StartupOS] Remote fetch failed for {f_name}: {net_e}")

        # 3. Last resort fallback to test mock if in test mode
        if not resolved:
            if frappe.flags.in_test or os.environ.get("FRAPPE_TEST"):
                with open(dest_file, "w", encoding="utf-8") as f:
                    if f_name == "compiler.py":
                        f.write(
                            "def compile_instance(profile_type, instance_name):\n    pass\n"
                        )
                    elif f_name == "parser.py":
                        f.write(
                            "def parse_questions_md(questions_path):\n    return {}\n"
                        )
                    else:
                        f.write("")
                resolved = True
                print(f"[StartupOS] Created test stub for missing module: {f_name}")
            else:
                raise RuntimeError(
                    f"Failed to load StartupOS core engine {f_name}. "
                    "File is missing locally and remote fetching is offline/unavailable."
                )

    if startup_os_root not in sys.path:
        sys.path.insert(0, startup_os_root)

    return startup_os_root


@frappe.whitelist()
def commit_onboarding_answers(profile_type, instance_name, answers, milestones=None):
    """
    Creates or updates the questions.md file for the given profile and instance name,
    runs the StartupOS compiler to render downstream deliverables, and commits
    the resulting plan to the database.
    """
    try:
        if profile_type not in ["business", "life"]:
            frappe.throw("Profile type must be 'business' or 'life'.")

        if not instance_name:
            frappe.throw("Instance name is required.")

        # Ensure core engines are loaded dynamically
        startup_os_root = ensure_startup_os_core()

        from core.compiler import compile_instance

        # Handle answers payload (deserialize if string)
        if isinstance(answers, str):
            answers = json.loads(answers)
        if milestones and isinstance(milestones, str):
            milestones = json.loads(milestones)

        # 1. Determine instance folder and write questions.md
        instance_dir = os.path.join(
            startup_os_root, "instances", profile_type, instance_name
        )
        os.makedirs(instance_dir, exist_ok=True)
        questions_path = os.path.join(instance_dir, "questions.md")

        # Human-friendly trading name
        display_name = re.sub(r"(?<=[a-z])(?=[A-Z])", " ", instance_name).strip()

        if profile_type == "business":
            trading_name = answers.get("trading_name") or display_name
            primary_base = answers.get("primary_base") or "Cape Town, South Africa"
            core_value_proposition = (
                answers.get("core_value_proposition") or "Pending — dynamic values."
            )
            customer_segments = answers.get("customer_segments") or "Pending."
            power_strategy = (
                answers.get("power_continuity_strategy") or "Off-grid solar."
            )
            y1 = answers.get("projected_year_1") or "Pending Year 1 projection."
            y2 = answers.get("projected_year_2") or "Pending Year 2 projection."
            y3 = answers.get("projected_year_3") or "Pending Year 3 projection."

            content = f"""# Business Strategic Questions: {trading_name}

This file is the Single Source of Truth (SSOT) for {trading_name}'s strategic, operational, and compliance variables.

---

## 1. Venture Identity & Foundations
*   **Trading Name**: What is the primary commercial brand or trading name?
    *   **Answer**: {trading_name}
*   **Primary Base**: What is your primary geographical base of operations?
    *   **Answer**: {primary_base}
*   **Core Value Proposition**: What is your product or service's unique value statement?
    *   **Answer**: {core_value_proposition}
*   **Customer Segments**: Who are the primary target users and demographic segments?
    *   **Answer**: {customer_segments}

---

## 2. Operations & Power Resilience
*   **Power Continuity Strategy**: How does your venture manage regional load shedding or grid failure?
    *   **Answer**: {power_strategy}

---

## 3. Financial Projections
*   **Projected Year 1**: What is the target Year 1 revenue and profit projection?
    *   **Answer**: {y1}
*   **Projected Year 2**: What is the target Year 2 revenue and profit projection?
    *   **Answer**: {y2}
*   **Projected Year 3**: What is the target Year 3 revenue and profit projection?
    *   **Answer**: {y3}
"""
        else:
            # life
            full_name = answers.get("full_name") or display_name
            gender = answers.get("gender") or "Male"
            primary_base = answers.get("primary_base") or "Cape Town, South Africa"
            life_purpose = answers.get("life_purpose") or "Pending purpose."
            wellness = answers.get("wellness_focus") or "Restore daily sleep depth."
            relationships = answers.get("key_relationships") or "Immediate family."
            legacy = answers.get("legacy_vision") or "Establish a generational legacy."
            ownership = answers.get("business_ownership") or "Pending."

            content = f"""# Life Strategic Questions: {full_name}

This file is the Single Source of Truth (SSOT) for {full_name}'s life development and tactical growth variables.

---

## 1. Personal Identity & Focus
*   **Full Name**: What is your full name?
    *   **Answer**: {full_name}
*   **Gender**: What is your gender?
    *   **Answer**: {gender}
*   **Primary Base**: What is your primary geographical base of operations?
    *   **Answer**: {primary_base}
*   **Life Purpose**: What is your high-level core mission or purpose statement?
    *   **Answer**: {life_purpose}
*   **Wellness Focus**: What is your primary wellness or biological high-performance goal?
    *   **Answer**: {wellness}

---

## 2. Relationships & Stewardship
*   **Key Relationships**: Who are the primary partners, confidants, or trustees in your life?
    *   **Answer**: {relationships}
*   **Legacy Vision**: What is the key long-term stewardship goal?
    *   **Answer**: {legacy}

---

## 3. Venture & Career Integration
*   **Business Ownership**: Do you own a registered business or run a side hustle?
    *   **Answer**: {ownership}
"""

        # Append milestones if provided
        if milestones:
            content += "\n\n## 4. Conversational Milestone Log (Living Ledger)\n"
            for m in milestones:
                m_date = m.get("date") or datetime.date.today().strftime("%Y-%m-%d")
                m_category = m.get("category") or "General"
                m_text = m.get("text") or ""
                if m_text:
                    content += f"\n*   **[{m_date}] ({m_category})**: {m_text}"

        with open(questions_path, "w", encoding="utf-8") as f:
            f.write(content)

        # 2. Trigger the dynamic compiler
        compile_instance(profile_type, instance_name)

        # 3. Save to database using type-aware commit_plan
        db_result = commit_plan(profile_type=profile_type, instance_name=instance_name)

        # 4. Mark onboarding complete for the Company / site
        try:
            companies = frappe.get_all("Company", limit_page_length=1)
            if companies:
                frappe.db.set_value(
                    "Company", companies[0].name, "onboarding_complete", 1
                )
                frappe.db.commit()
        except Exception as e:
            frappe.log_error(f"Failed to set onboarding_complete: {e}")

        return {
            "status": "success",
            "message": "Questions committed, compiled, and database plan updated successfully.",
            "db_result": db_result,
        }

    except Exception as e:
        frappe.log_error(frappe.get_traceback(), "commit_onboarding_answers Error")
        return {"status": "error", "message": str(e)}


@frappe.whitelist()
def commit_plan(plan_data=None, profile_type=None, instance_name=None):
    """
    Accepts either raw JSON payload from frontend (backward compatibility)
    or profile_type + instance_name to read parsed answers from questions.md and feed the DB.
    """
    try:
        # Determine standard StartupOS paths and imports
        startup_os_root = ensure_startup_os_core()
        from core.parser import parse_questions_md

        # 1. Clear existing plan if any to avoid duplication
        plan_doc = frappe.get_doc("Plan On A Page")
        if plan_doc.vision:
            old_vision = plan_doc.vision
            # Delete old KPIs, Objectives, and Pillars linked to this Vision
            pillars = frappe.get_all("Pillar", filters={"vision": old_vision})
            for p in pillars:
                objectives = frappe.get_all(
                    "Strategic Objective", filters={"pillar": p.name}
                )
                for o in objectives:
                    frappe.db.delete("KPI", {"strategic_objective": o.name})
                frappe.db.delete("Strategic Objective", {"pillar": p.name})
            frappe.db.delete("Pillar", {"vision": old_vision})
            frappe.db.delete("Vision", {"name": old_vision})

            plan_doc.vision = None
            plan_doc.save(ignore_permissions=True)

        # 2. Case A: Raw plan_data passed (backward compatibility)
        if plan_data:
            data = json.loads(plan_data)

            # Create the Vision
            vision_doc = frappe.new_doc("Vision")
            vision_doc.title = data.get("vision_title")
            vision_doc.description = data.get("vision_description")
            vision_doc.insert(ignore_permissions=True)

            # Create Pillars, Objectives, KPIs
            for pillar_data in data.get("pillars", []):
                pillar_doc = frappe.new_doc("Pillar")
                pillar_doc.title = pillar_data.get("title")
                pillar_doc.description = pillar_data.get("description")
                pillar_doc.vision = vision_doc.name
                pillar_doc.insert(ignore_permissions=True)

                for objective_data in pillar_data.get("objectives", []):
                    objective_doc = frappe.new_doc("Strategic Objective")
                    objective_doc.title = objective_data.get("title")
                    objective_doc.description = objective_data.get("description")
                    objective_doc.pillar = pillar_doc.name
                    objective_doc.insert(ignore_permissions=True)

                    for kpi_data in objective_data.get("kpis", []):
                        kpi_doc = frappe.new_doc("KPI")
                        kpi_doc.title = kpi_data.get("title")
                        kpi_doc.description = kpi_data.get("description")
                        kpi_doc.strategic_objective = objective_doc.name
                        kpi_doc.insert(ignore_permissions=True)

            plan_doc.vision = vision_doc.name
            plan_doc.save(ignore_permissions=True)
            return {
                "status": "success",
                "message": "Plan on a Page created successfully.",
            }

        # 3. Case B: Profile type and instance name passed (read from questions.md)
        if not profile_type or not instance_name:
            frappe.throw(
                "Invalid arguments. Must supply either plan_data or profile_type + instance_name."
            )

        questions_path = os.path.join(
            startup_os_root, "instances", profile_type, instance_name, "questions.md"
        )
        if not os.path.exists(questions_path):
            frappe.throw(f"StartupOS questions.md not found at: {questions_path}")

        # Parse questions.md
        q_data = parse_questions_md(questions_path)
        display_name = re.sub(r"(?<=[a-z])(?=[A-Z])", " ", instance_name).strip()

        # Build Vision, Pillars, Objectives, KPIs based on type
        if profile_type == "business":
            trading_name = q_data.get("trading_name") or display_name
            core_value_proposition = (
                q_data.get("core_value_proposition") or "Pending core values."
            )
            customer_segments = (
                q_data.get("customer_segments") or "Pending target market."
            )
            power_strategy = (
                q_data.get("power_continuity_strategy")
                or "Pending operations strategy."
            )
            y1 = q_data.get("projected_year_1") or "Pending Year 1."
            y2 = q_data.get("projected_year_2") or "Pending Year 2."
            y3 = q_data.get("projected_year_3") or "Pending Year 3."

            # Create Vision
            vision_doc = frappe.new_doc("Vision")
            vision_doc.title = f"Vision: {trading_name}"
            vision_doc.description = f"Core Mission: To deliver alternative bookkeeping and supply chain orchestration for unbanked micro-merchants.\n\nValue Proposition: {core_value_proposition}"
            vision_doc.insert(ignore_permissions=True)

            # Pillar 1: Identity & Customer Foundations
            p1 = frappe.new_doc("Pillar")
            p1.title = "Identity & Customer Foundations"
            p1.description = "Establish clear enterprise brand status and validate addressable customer segments."
            p1.vision = vision_doc.name
            p1.insert(ignore_permissions=True)

            o1_1 = frappe.new_doc("Strategic Objective")
            o1_1.title = "Validate Customer Segments"
            o1_1.description = f"Target segment definition: {customer_segments}"
            o1_1.pillar = p1.name
            o1_1.insert(ignore_permissions=True)

            o1_2 = frappe.new_doc("Strategic Objective")
            o1_2.title = "Deliver Core Value Proposition"
            o1_2.description = f"Commercial value validation: {core_value_proposition}"
            o1_2.pillar = p1.name
            o1_2.insert(ignore_permissions=True)

            # Pillar 2: Operations & Resilience
            p2 = frappe.new_doc("Pillar")
            p2.title = "Operations & Resilience"
            p2.description = "Robust off-grid execution and backup power/continuity resilience framework."
            p2.vision = vision_doc.name
            p2.insert(ignore_permissions=True)

            o2_1 = frappe.new_doc("Strategic Objective")
            o2_1.title = "Ensure Power Continuity"
            o2_1.description = f"Power strategy: {power_strategy}"
            o2_1.pillar = p2.name
            o2_1.insert(ignore_permissions=True)

            # Pillar 3: Financial Projections & Targets
            p3 = frappe.new_doc("Pillar")
            p3.title = "Financial Projections & Targets"
            p3.description = "3-year high-fidelity strategic performance milestones."
            p3.vision = vision_doc.name
            p3.insert(ignore_permissions=True)

            o3_1 = frappe.new_doc("Strategic Objective")
            o3_1.title = "Achieve Year 1 Milestone"
            o3_1.description = f"Financial Projection: {y1}"
            o3_1.pillar = p3.name
            o3_1.insert(ignore_permissions=True)

            o3_2 = frappe.new_doc("Strategic Objective")
            o3_2.title = "Achieve Year 2 Milestone"
            o3_2.description = f"Financial Projection: {y2}"
            o3_2.pillar = p3.name
            o3_2.insert(ignore_permissions=True)

            o3_3 = frappe.new_doc("Strategic Objective")
            o3_3.title = "Achieve Year 3 Milestone"
            o3_3.description = f"Financial Projection: {y3}"
            o3_3.pillar = p3.name
            o3_3.insert(ignore_permissions=True)

        else:
            # life
            full_name = q_data.get("full_name") or display_name
            life_purpose = q_data.get("life_purpose") or "Pending core purpose."
            wellness = q_data.get("wellness_focus") or "Restore sleep metrics."
            relationships = q_data.get("key_relationships") or "Immediate family."
            legacy = q_data.get("legacy_vision") or "Generational stewardship."
            ownership = q_data.get("business_ownership") or "Pending ownership."

            # Create Vision
            vision_doc = frappe.new_doc("Vision")
            vision_doc.title = f"Life Purpose: {full_name}"
            vision_doc.description = life_purpose
            vision_doc.insert(ignore_permissions=True)

            # Pillar 1: Personal Identity & Wellness
            p1 = frappe.new_doc("Pillar")
            p1.title = "Personal Identity & Wellness"
            p1.description = "Nurture physical, mental, and spiritual mastery."
            p1.vision = vision_doc.name
            p1.insert(ignore_permissions=True)

            o1_1 = frappe.new_doc("Strategic Objective")
            o1_1.title = "Optimize Physical Conditioning"
            o1_1.description = f"Wellness focus: {wellness}"
            o1_1.pillar = p1.name
            o1_1.insert(ignore_permissions=True)

            # Pillar 2: Relationships & Stewardship
            p2 = frappe.new_doc("Pillar")
            p2.title = "Relationships & Stewardship"
            p2.description = "Build evergreen partnership bonds and safeguard generational legacy assets."
            p2.vision = vision_doc.name
            p2.insert(ignore_permissions=True)

            o2_1 = frappe.new_doc("Strategic Objective")
            o2_1.title = "Strengthen Key Relationships"
            o2_1.description = f"Primary partners: {relationships}"
            o2_1.pillar = p2.name
            o2_1.insert(ignore_permissions=True)

            o2_2 = frappe.new_doc("Strategic Objective")
            o2_2.title = "Secure Generational Legacy"
            o2_2.description = f"Legacy vision: {legacy}"
            o2_2.pillar = p2.name
            o2_2.insert(ignore_permissions=True)

            # Pillar 3: Venture & Career Integration
            p3 = frappe.new_doc("Pillar")
            p3.title = "Venture & Career Integration"
            p3.description = (
                "Align commercial activities with broader personal growth plans."
            )
            p3.vision = vision_doc.name
            p3.insert(ignore_permissions=True)

            o3_1 = frappe.new_doc("Strategic Objective")
            o3_1.title = "Integrate Business & Career Growth"
            o3_1.description = f"Business ownership details: {ownership}"
            o3_1.pillar = p3.name
            o3_1.insert(ignore_permissions=True)

        plan_doc.vision = vision_doc.name
        plan_doc.save(ignore_permissions=True)

        # Create Company Policies or Personal Goals based on parsed answers
        if profile_type == "business":
            # Check and create default company policies if needed
            policy_title = f"{trading_name} Strategic Alignment Policy"
            if not frappe.db.exists("Company Policy", policy_title):
                policy_doc = frappe.new_doc("Company Policy")
                policy_doc.title = policy_title
                policy_doc.description = f"Enterprise-wide mandate to pursue: {core_value_proposition}\n\nPower Resilience Strategy: {power_strategy}"
                policy_doc.insert(ignore_permissions=True)
        else:
            # life
            goal_title = f"{full_name}: Wellness Mastery"
            if not frappe.db.exists("Personal Mastery Goal", goal_title):
                goal_doc = frappe.new_doc("Personal Mastery Goal")
                goal_doc.title = goal_title
                goal_doc.description = f"Physical condition focus: {wellness}"
                goal_doc.insert(ignore_permissions=True)

        return {
            "status": "success",
            "message": "Plan on a Page committed from questions.md successfully.",
        }

    except Exception as e:
        frappe.log_error(frappe.get_traceback(), "commit_plan Error")
        return {"status": "error", "message": str(e)}


@frappe.whitelist()
def chat_with_rok(message, session_id=None, model=None):
    """
    Secure gateway proxy for Next.js (Vercel) to chat with ROK agent on the Tenant VPS.
    """
    try:
        # Check if ROK is enabled for this subscription tier
        from rcore.utils.subscription_checker import get_cached_subscription_details

        sub = get_cached_subscription_details()
        if sub.get("is_free_plan", 0) or not sub.get("is_ai", 0):
            # Enforce 5 free messages daily limit
            user_id = frappe.session.user
            today_date = datetime.date.today().strftime("%Y-%m-%d")
            cache_key = f"free_rok_msg_count:{user_id}:{today_date}"
            current_count = frappe.cache().get_value(cache_key) or 0
            if current_count >= 5:
                frappe.throw(
                    "Quota Exceeded: Your daily free conversational ROK quota is complete! To make sure you don't lose any of the progress we've made, we are switching your Strategic Onboarding to Predefined (Offline) Mode. You can continue answering the remaining questions statically. To reactivate my smart auditing and reasoning right now, upgrade to a Pro plan!",
                    frappe.PermissionError,
                )
            frappe.cache().set_value(cache_key, current_count + 1, expires_in_sec=86400)

        # Secure seat assignment and license gatekeeping
        from rcore.tenant.api import get_token_usage

        usage_tracker = get_token_usage()
        if usage_tracker.get("seat_limit_exceeded"):
            frappe.throw(
                "Your team's ROK seat limit has been reached. Please contact your administrator to upgrade your subscription.",
                frappe.PermissionError,
            )

        url = "http://127.0.0.1:8642/v1/chat/completions"
        headers = {
            "Content-Type": "application/json",
        }
        if session_id:
            headers["X-Hermes-Session-Id"] = session_id

        # Securely isolate memory context per user in multi-tenant environment
        user_id = frappe.session.user
        if user_id:
            headers["X-Hermes-User-Id"] = user_id

        payload = {
            "model": model or "hermes-agent",
            "messages": [{"role": "user", "content": message}],
            "stream": False,
        }

        import requests

        response = requests.post(url, json=payload, headers=headers, timeout=60.0)
        response.raise_for_status()

        result = response.json()
        choices = result.get("choices", [])
        if choices:
            return {
                "status": "success",
                "message": choices[0].get("message", {}).get("content", ""),
                "tool_calls": choices[0].get("message", {}).get("tool_calls", None),
                "session_id": session_id,
            }
        return {"status": "error", "message": "No response choice returned from ROK."}

    except Exception as e:
        frappe.log_error(f"ROK Tenant Chat Bridge failed: {e}")
        return {"status": "error", "message": str(e)}


@frappe.whitelist()
def summarize_chat_session(session_id, messages):
    """
    Summarizes a completed or long chat session via the ROK completions loop on Tenant.
    """
    try:
        url = "http://127.0.0.1:8642/v1/chat/completions"
        headers = {
            "Content-Type": "application/json",
        }
        if session_id:
            headers["X-Hermes-Session-Id"] = session_id

        # Securely isolate memory context per user in multi-tenant environment
        user_id = frappe.session.user
        if user_id:
            headers["X-Hermes-User-Id"] = user_id

        # Decode messages if they are passed as JSON string
        if isinstance(messages, str):
            try:
                import json

                messages = json.loads(messages)
            except Exception:
                pass

        system_prompt = (
            "Provide a concise, high-level summary of the preceding conversation "
            "highlighting the core user goals, preferences, and strategic answers collected. "
            "This summary will serve as the golden thread context for future sessions."
        )

        payload = {
            "model": "hermes-agent",
            "messages": [
                {"role": "system", "content": system_prompt},
                {
                    "role": "user",
                    "content": f"Here is the conversation to summarize:\n{json.dumps(messages, indent=2)}",
                },
            ],
            "stream": False,
        }

        import requests

        response = requests.post(url, json=payload, headers=headers, timeout=60.0)
        response.raise_for_status()

        result = response.json()
        choices = result.get("choices", [])
        if choices:
            summary = choices[0].get("message", {}).get("content", "")
            # Save Engram memory if brain app exists
            if frappe.db.exists("DocType", "Engram"):
                engram_name = f"chat-summary-{session_id}"
                if not frappe.db.exists("Engram", engram_name):
                    engram = frappe.new_doc("Engram")
                    engram.reference_doctype = "Chat Session"
                    engram.reference_name = session_id
                    engram.reference_title = f"Chat Session Summary: {session_id}"
                    engram.summary = summary
                    engram.insert(ignore_permissions=True)
                else:
                    engram = frappe.get_doc("Engram", engram_name)
                    engram.summary = summary
                    engram.save(ignore_permissions=True)

            return {"status": "success", "summary": summary}
        return {"status": "error", "message": "No summary choice returned from ROK."}

    except Exception as e:
        frappe.log_error(f"ROK Summarization failed: {e}")
        return {"status": "error", "message": str(e)}


@frappe.whitelist(allow_guest=True)
def get_available_models():
    """
    Returns available AI models configured on the backend (Single Source of Truth)
    """
    models_file = os.path.join(os.path.dirname(__file__), "models.json")
    if os.path.exists(models_file):
        try:
            with open(models_file, "r", encoding="utf-8") as f:
                return json.load(f)
        except Exception as e:
            frappe.log_error(
                f"Failed to read models.json: {str(e)}", "AI Models Configuration"
            )
    return {}
