# Copyright (c) 2026, Rokct Intelligence (pty) Ltd.
# For license information, please see license.txt


import json
import frappe
import os
import urllib.request
import urllib.parse


def perform_bootstrap_secrets_handshake():
    """
    Performs secure single-use bootstrap handshake.
    Exchanges the transient ROKCT_BOOTSTRAP_TOKEN for AI credentials,
    loads them strictly in-memory, and immediately deletes the token.
    """
    token = os.environ.get("ROKCT_BOOTSTRAP_TOKEN")
    if not token:
        return

    # Check if already completed to avoid repeated network calls
    if frappe.cache().get_value("bootstrap_completed"):
        os.environ.pop("ROKCT_BOOTSTRAP_TOKEN", None)
        return

    control_url = os.environ.get("ROKCT_CONTROL_URL") or "https://platform.rokct.ai"
    target_endpoint = (
        f"{control_url}/api/method/control.control.bootstrap.get_bootstrap_secrets"
    )

    try:
        data = urllib.parse.urlencode({"token": token}).encode("utf-8")
        req = urllib.request.Request(
            target_endpoint,
            data=data,
            headers={
                "User-Agent": "ROKCT-Bootstrap-Agent/1.0",
                "Content-Type": "application/x-www-form-urlencoded",
            },
        )

        with urllib.request.urlopen(req, timeout=10) as response:
            res_data = json.loads(response.read().decode("utf-8"))
            secrets = res_data.get("message")

            if secrets:
                # Load keys strictly in-memory in environment & site config
                if secrets.get("gemini_api_key"):
                    os.environ["GEMINI_API_KEY"] = secrets["gemini_api_key"]
                    frappe.local.conf.gemini_api_key = secrets["gemini_api_key"]
                if secrets.get("openai_api_key"):
                    os.environ["OPENAI_API_KEY"] = secrets["openai_api_key"]
                    frappe.local.conf.openai_api_key = secrets["openai_api_key"]
                if secrets.get("whatsapp_bridge_url"):
                    os.environ["WHATSAPP_BRIDGE_URL"] = secrets["whatsapp_bridge_url"]
                    frappe.local.conf.whatsapp_bridge_url = secrets[
                        "whatsapp_bridge_url"
                    ]
                if secrets.get("tenant_id"):
                    os.environ["TENANT_ID"] = secrets["tenant_id"]
                    frappe.local.conf.tenant_id = secrets["tenant_id"]

                # Auto-initialize ROK configuration files so ROK is instantly pre-configured out of the box
                try:
                    import pathlib

                    rok_home = pathlib.Path.home() / ".rok"
                    rok_home.mkdir(parents=True, exist_ok=True)

                    # 1. Write secure ~/.rok/.env (API Keys)
                    env_file = rok_home / ".env"
                    env_lines = []
                    if secrets.get("gemini_api_key"):
                        env_lines.append(f"GEMINI_API_KEY={secrets['gemini_api_key']}")
                        env_lines.append(f"GOOGLE_API_KEY={secrets['gemini_api_key']}")
                    if secrets.get("openai_api_key"):
                        env_lines.append(f"OPENAI_API_KEY={secrets['openai_api_key']}")
                    if secrets.get("whatsapp_bridge_url"):
                        env_lines.append(
                            f"WHATSAPP_BRIDGE_URL={secrets['whatsapp_bridge_url']}"
                        )

                    with open(env_file, "w", encoding="utf-8") as f:
                        f.write("\n".join(env_lines) + "\n")
                    env_file.chmod(0o600)

                    # 2. Write ~/.rok/config.yaml (Default Model and Provider)
                    config_file = rok_home / "config.yaml"
                    if not config_file.exists():
                        # Read available models dynamically from backend models.json SSOT
                        models_config = {}
                        models_file = os.path.join(
                            os.path.dirname(__file__), "models.json"
                        )
                        if os.path.exists(models_file):
                            try:
                                with open(models_file, "r", encoding="utf-8") as f:
                                    models_config = json.load(f)
                            except Exception:
                                pass

                        raw_model_id = models_config.get("PAID", {}).get(
                            "id", "gemini-3-pro"
                        )
                        default_model = (
                            f"google/{raw_model_id}"
                            if "gemini" in raw_model_id
                            else raw_model_id
                        )

                        config_content = f"""# Automatically generated by ROKCT Bootstrap Handshake
model: "{default_model}"
providers: {{}}
agent:
  max_turns: 90
terminal:
  backend: local
"""
                        with open(config_file, "w", encoding="utf-8") as f:
                            f.write(config_content)
                        config_file.chmod(0o600)
                except Exception as ex:
                    frappe.log_error(
                        f"ROKCT ROK Auto-Config seeding failed: {str(ex)}",
                        "Bootstrap Security",
                    )

                frappe.cache().set_value("bootstrap_completed", 1)

    except Exception as e:
        frappe.log_error(
            f"ROKCT Bootstrap handshake failed: {str(e)}", "Bootstrap Security"
        )
    finally:
        # Strictly purge transient token from process memory space
        os.environ.pop("ROKCT_BOOTSTRAP_TOKEN", None)
